"""groups

Revision ID: 8ac4dd99d193
Revises:
Create Date: 2023-12-13 17:45:55.984092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ac4dd99d193'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('groupName', sa.String(length=500),
                              nullable=True),
                    sa.Column('groupBio', sa.String(length=1000),
                              nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('groupName'))
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(length=500),
                              nullable=True),
                    sa.Column('password', sa.String(length=500),
                              nullable=True),
                    sa.Column('firstName', sa.String(length=500),
                              nullable=True),
                    sa.Column('secondName', sa.String(length=500),
                              nullable=True),
                    sa.Column('weight', sa.Integer(), nullable=True),
                    sa.Column('height', sa.Integer(), nullable=True),
                    sa.Column('squat', sa.Integer(), nullable=True),
                    sa.Column('bench', sa.Integer(), nullable=True),
                    sa.Column('deadlift', sa.Integer(), nullable=True),
                    sa.Column('profile_image', sa.String(length=20),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('username'))
    op.create_table('user_group_association',
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('group_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_group_association')
    op.drop_table('users')
    op.drop_table('groups')
    # ### end Alembic commands ###
